In [97]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [98]:
df=pd.read_csv("Toyota.csv",index_col=0,na_values=["??","????","##"])

In [99]:
df_main=df.apply(lambda x:x.fillna(x.mean()) if x.dtype=="float"
                 else x.fillna(x.value_counts().index[0]))

In [100]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1436 non-null   float64
 2   KM         1436 non-null   float64
 3   FuelType   1436 non-null   object
 4   HP         1436 non-null   float64
 5   MetColor   1436 non-null   float64
 6   Automatic  1436 non-null   int64
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   object
 9   Weight     1436 non-null   int64
dtypes: float64(4), int64(4), object(2)
memory usage: 123.4+ KB

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1336 non-null   float64
 2   KM         1421 non-null   float64
 3   FuelType   1336 non-null   object
 4   HP         1430 non-null   float64
 5   MetColor   1286 non-null   float64
 6   Automatic  1436 non-null   int64
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   object
 9   Weight     1436 non-null   int64
dtypes: float64(4), int64(4), object(2)
memory usage: 123.4+ KB

In [74]:
df["KM"].astype("float")

0       46986.0
1       72937.0
2       41711.0
3       48000.0
4       38500.0
         ...
1431    20544.0
1432        NaN
1433    17016.0
1434        NaN
1435        1.0
Name: KM, Length: 1436, dtype: float64

In [75]:

df.isna().sum()

Price          0
Age          100
KM            15
FuelType     100
HP             6
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [76]:
df.isnull().sum()

Price          0
Age          100
KM            15
FuelType     100
HP             6
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [77]:
missing=df[df.isnull().any(axis=1)]

In [78]:
missing.shape

(340, 10)

In [79]:
df.describe()

,Price,Age,KM,HP,MetColor,Automatic,CC,Weight
count,1436.000000,1336.000000,1421.000000,1430.000000,1286.000000,1436.000000,1436.000000,1436.00000
mean,10730.824513,55.672156,68647.239972,101.478322,0.674961,0.055710,1566.827994,1072.45961
std,3626.964585,18.589804,37333.023589,14.768255,0.468572,0.229441,187.182436,52.64112
min,4350.000000,1.000000,1.000000,69.000000,0.000000,0.000000,1300.000000,1000.00000
25%,8450.000000,43.000000,43210.000000,90.000000,0.000000,0.000000,1400.000000,1040.00000
50%,9900.000000,60.000000,63634.000000,110.000000,1.000000,0.000000,1600.000000,1070.00000
75%,11950.000000,70.000000,87000.000000,110.000000,1.000000,0.000000,1600.000000,1085.00000
max,32500.000000,80.000000,243000.000000,192.000000,1.000000,1.000000,2000.000000,1615.00000

In [80]:
missing.describe()

,Price,Age,KM,HP,MetColor,Automatic,CC,Weight
count,340.000000,240.000000,325.000000,334.000000,190.000000,340.000000,340.000000,340.000000
mean,10714.344118,55.720833,66551.058462,100.401198,0.684211,0.064706,1560.267647,1069.373529
std,3600.625916,18.117272,34703.936722,13.826927,0.466058,0.246369,196.059174,55.192491
min,5800.000000,8.000000,1.000000,69.000000,0.000000,0.000000,1300.000000,1000.000000
25%,8450.000000,43.750000,42000.000000,86.000000,0.000000,0.000000,1400.000000,1035.000000
50%,9950.000000,61.000000,64000.000000,110.000000,1.000000,0.000000,1600.000000,1062.500000
75%,11787.500000,69.250000,84000.000000,110.000000,1.000000,0.000000,1600.000000,1080.000000
max,32500.000000,80.000000,204250.000000,192.000000,1.000000,1.000000,2000.000000,1480.000000

In [81]:
df["Age"].mean()

np.float64(55.67215568862275)

In [82]:
df["Age"].fillna(df["Age"].mean(),inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_4480\2595122914.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1436 non-null   float64
 2   KM         1421 non-null   float64
 3   FuelType   1336 non-null   object
 4   HP         1430 non-null   float64
 5   MetColor   1286 non-null   float64
 6   Automatic  1436 non-null   int64
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   object
 9   Weight     1436 non-null   int64
dtypes: float64(4), int64(4), object(2)
memory usage: 123.4+ KB

In [84]:
df["KM"].median()

63634.0

In [85]:
df["KM"].fillna(df["KM"].median(),inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_4480\572988085.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["KM"].fillna(df["KM"].median(),inplace=True)

In [86]:

df["HP"].fillna(df["HP"].mean(),inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_4480\3944235765.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["HP"].fillna(df["HP"].mean(),inplace=True)

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1436 non-null   float64
 2   KM         1436 non-null   float64
 3   FuelType   1336 non-null   object
 4   HP         1436 non-null   float64
 5   MetColor   1286 non-null   float64
 6   Automatic  1436 non-null   int64
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   object
 9   Weight     1436 non-null   int64
dtypes: float64(4), int64(4), object(2)
memory usage: 123.4+ KB

In [88]:
df.isnull().sum()

Price          0
Age            0
KM             0
FuelType     100
HP             0
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [89]:
df["FuelType"].value_counts().index[0]

'Petrol'

In [90]:
df["FuelType"].fillna(df["FuelType"].value_counts().index[0],inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_4480\1807326957.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["FuelType"].fillna(df["FuelType"].value_counts().index[0],inplace=True)

In [91]:
df["MetColor"].mode()

0    1.0
Name: MetColor, dtype: float64

In [92]:
df["MetColor"].fillna(df["MetColor"].mode().index[0],inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_4480\2895049678.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["MetColor"].fillna(df["MetColor"].mode().index[0],inplace=True)

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1436 non-null   float64
 2   KM         1436 non-null   float64
 3   FuelType   1436 non-null   object
 4   HP         1436 non-null   float64
 5   MetColor   1436 non-null   float64
 6   Automatic  1436 non-null   int64
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   object
 9   Weight     1436 non-null   int64
dtypes: float64(4), int64(4), object(2)
memory usage: 123.4+ KB

In [94]:
df["HP"]

0        90.0
1        90.0
2        90.0
3        90.0
4        90.0
        ...
1431     86.0
1432     86.0
1433     86.0
1434     86.0
1435    110.0
Name: HP, Length: 1436, dtype: float64

In [95]:
df["HP"].mean()

np.float64(101.47832167832168)

In [96]:
df.isnull().sum()

Price        0
Age          0
KM           0
FuelType     0
HP           0
MetColor     0
Automatic    0
CC           0
Doors        0
Weight       0
dtype: int64

In [ ]:
df3=df