In [68]:
import pandas as pd
import numpy as np

In [69]:
df=pd.read_csv('Toyota.csv',index_col=0,na_values=["??","????","##"])

In [70]:
df.head()

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.0,46986.0,Diesel,90.0,1.0,0,2000,three,1165
1,13750,23.0,72937.0,Diesel,90.0,1.0,0,2000,3,1165
2,13950,24.0,41711.0,Diesel,90.0,NaN,0,2000,3,1165
3,14950,26.0,48000.0,Diesel,90.0,0.0,0,2000,3,1165
4,13750,30.0,38500.0,Diesel,90.0,0.0,0,2000,3,1170

In [47]:
df.at[4,"MetColor"]

np.float64(0.0)

In [48]:
df.iat[4,5]

np.float64(0.0)

In [49]:
df.at[4,"FuelType"]

'Diesel'

In [50]:
df.iat[4,3]

'Diesel'

In [51]:
df.loc[1,"MetColor"]

np.float64(1.0)

In [52]:
df.iloc[:,[2]]

           KM
0     46986.0
1     72937.0
2     41711.0
3     48000.0
4     38500.0
...       ...
1431  20544.0
1432      NaN
1433  17016.0
1434      NaN
1435      1.0

[1436 rows x 1 columns]

In [53]:
df.memory_usage()

Index        44552
Price        11488
Age          11488
KM           11488
FuelType     11488
HP           11488
MetColor     11488
Automatic    11488
CC           11488
Doors        11488
Weight       11488
dtype: int64

In [22]:
df.ndim

2

In [23]:
samp=df.copy(deep=False)

In [24]:
deep=df.copy(deep=True)

In [27]:
deep.index

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435],
      dtype='int64', length=1436)

In [29]:

deep.columns

Index(['Price', 'Age', 'KM', 'FuelType', 'HP', 'MetColor', 'Automatic', 'CC',
       'Doors', 'Weight'],
      dtype='object')

In [30]:
deep.memory_usage(['Index'])

Index        44552
Price        11488
Age          11488
KM           11488
FuelType     11488
HP           11488
MetColor     11488
Automatic    11488
CC           11488
Doors        11488
Weight       11488
dtype: int64

In [32]:
df.astype('object')

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.0,46986.0,Diesel,90.0,1.0,0,2000,three,1165
1,13750,23.0,72937.0,Diesel,90.0,1.0,0,2000,3,1165
2,13950,24.0,41711.0,Diesel,90.0,NaN,0,2000,3,1165
3,14950,26.0,48000.0,Diesel,90.0,0.0,0,2000,3,1165
4,13750,30.0,38500.0,Diesel,90.0,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,NaN,20544.0,Petrol,86.0,1.0,0,1300,3,1025
1432,10845,72.0,NaN,Petrol,86.0,0.0,0,1300,3,1015
1433,8500,NaN,17016.0,Petrol,86.0,0.0,0,1300,3,1015
1434,7250,70.0,NaN,NaN,86.0,1.0,0,1300,3,1015
1435,6950,76.0,1.0,Petrol,110.0,0.0,0,1600,5,1114

In [40]:
df['FuelType'].astype('category')

In [41]:
df

0       Diesel
1       Diesel
2       Diesel
3       Diesel
4       Diesel
         ...
1431    Petrol
1432    Petrol
1433    Petrol
1434       NaN
1435    Petrol
Name: FuelType, Length: 1436, dtype: category
Categories (3, object): ['CNG', 'Diesel', 'Petrol']

In [34]:
dt={1:2,3:4}

In [36]:
dt.keys()

dict_keys([1, 3])

In [37]:
dt.values()

dict_values([2, 4])

In [54]:

df.get_dtype_countsdf["Category"] = df["Category"].astype("category")
()

AttributeError: 'DataFrame' object has no attribute 'get_dtype_counts'

In [71]:
df["FuelType"] = df["FuelType"].astype("category")

In [73]:
df.select_dtypes(include="number")

      Price   Age       KM     HP  MetColor  Automatic    CC  Weight
0     13500  23.0  46986.0   90.0       1.0          0  2000    1165
1     13750  23.0  72937.0   90.0       1.0          0  2000    1165
2     13950  24.0  41711.0   90.0       NaN          0  2000    1165
3     14950  26.0  48000.0   90.0       0.0          0  2000    1165
4     13750  30.0  38500.0   90.0       0.0          0  2000    1170
...     ...   ...      ...    ...       ...        ...   ...     ...
1431   7500   NaN  20544.0   86.0       1.0          0  1300    1025
1432  10845  72.0      NaN   86.0       0.0          0  1300    1015
1433   8500   NaN  17016.0   86.0       0.0          0  1300    1015
1434   7250  70.0      NaN   86.0       1.0          0  1300    1015
1435   6950  76.0      1.0  110.0       0.0          0  1600    1114

[1436 rows x 8 columns]

In [74]:
df.select_dtypes(include="object")

      Doors
0     three
1         3
2         3
3         3
4         3
...     ...
1431      3
1432      3
1433      3
1434      3
1435      5

[1436 rows x 1 columns]

In [78]:
df.dtype

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [77]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C"],        # object (string)
    "Age": [20, 25, 30],            # int
    "Category": pd.Series(["X","Y","Z"], dtype="category")  # category
})

df.select_dtypes(include="category")

  Category
0        X
1        Y
2        Z

In [ ]:
df.get_dtype_counts()